# 1. Start with the freshly-built local Fyros image
FROM localhost/fyros:latest AS base

# 2. Rip the pre-compiled OPEN drivers from Universal Blue's server
# (Using main-44 to match the Fedora 44 base kernel)
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:main-44 /rpms/ /tmp/nvidia-rpms/

# 3. Install the drivers and clean up
RUN set -x && \
    # Install the Universal Blue Nvidia addons (This automatically configures the kernel arguments!)
    dnf5 install -y /tmp/nvidia-rpms/ublue-os/ublue-os-nvidia*.rpm && \
    # Install the actual Nvidia Kernel Modules
    dnf5 install -y /tmp/nvidia-rpms/kmods/kmod-nvidia*.rpm && \
    # Clean up the temporary RPMs to keep the image size optimized
    rm -rf /tmp/nvidia-rpms && \
    dnf5 clean all

### LINTING
## Verify the Nvidia layered image is correct.
RUN bootc container lint
