[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty.conf"
output_path = "~/.config/ghostty/dms-colors.conf"

[templates.dgop]
input_path = "~/.config/matugen/templates/dgop.json"
output_path = "~/.config/dgop/colors.json"
